# Use the official Node.js 20 image.
# https://hub.docker.com/_/node
FROM node:18.20.2-buster

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

RUN apt-get update
RUN apt-get upgrade

# RUN apt-get install -y libnss3

RUN npm install

# Copy local code to the container image.
COPY . .

# Expose port 3000 for the application.
EXPOSE 3000

# Run the web service on container startup.
CMD [ "node", "bot.js" ]